# Generated by Django 4.2.20 on 2025-05-15 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 15, 20, 48, 906340, tzinfo=datetime.timezone.utc)),
        ),
    ]
